// flow-typed signature: f9f49a16d740ed3c1e25c6446ce0753c
// flow-typed version: <<STUB>>/basic-auth_v^1.0.4/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'basic-auth'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'basic-auth' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'basic-auth/index' {
  declare module.exports: $Exports<'basic-auth'>;
}
declare module 'basic-auth/index.js' {
  declare module.exports: $Exports<'basic-auth'>;
}
