// flow-typed signature: 21a430cde194c6267268103a0d810b2e
// flow-typed version: <<STUB>>/browser-update_v^2.1.6/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browser-update'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browser-update' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browser-update/update.npm.full' {
  declare module.exports: any;
}

declare module 'browser-update/update.npm' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browser-update/update.npm.full.js' {
  declare module.exports: $Exports<'browser-update/update.npm.full'>;
}
declare module 'browser-update/update.npm.js' {
  declare module.exports: $Exports<'browser-update/update.npm'>;
}
