// flow-typed signature: dd7a452f4a8d9398e4c82150a6df5a69
// flow-typed version: <<STUB>>/country-list_v^1.1.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'country-list'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'country-list' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'country-list/country-list' {
  declare module.exports: any;
}

// Filename aliases
declare module 'country-list/country-list.js' {
  declare module.exports: $Exports<'country-list/country-list'>;
}
