// flow-typed signature: 7f20e75c63574d1a538412cbc426e7da
// flow-typed version: <<STUB>>/eslint-plugin-no-unused-vars-rest_v^1.0.4/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-no-unused-vars-rest'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-no-unused-vars-rest' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-no-unused-vars-rest/dist/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-no-unused-vars-rest/dist/rules/no-unused-vars' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-no-unused-vars-rest/dist/index.js' {
  declare module.exports: $Exports<'eslint-plugin-no-unused-vars-rest/dist/index'>;
}
declare module 'eslint-plugin-no-unused-vars-rest/dist/rules/no-unused-vars.js' {
  declare module.exports: $Exports<'eslint-plugin-no-unused-vars-rest/dist/rules/no-unused-vars'>;
}
