// flow-typed signature: b1a9f05ba570c6634a213953411f3069
// flow-typed version: <<STUB>>/scut_v^1.4.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'scut'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'scut' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'scut/lib/eyeglass-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'scut/lib/eyeglass-exports.js' {
  declare module.exports: $Exports<'scut/lib/eyeglass-exports'>;
}
