// flow-typed signature: da2df08f9a0c1f8442e64a4a61896272
// flow-typed version: <<STUB>>/sentry-cli-binary_v^1.22.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sentry-cli-binary'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sentry-cli-binary' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'sentry-cli-binary/index' {
  declare module.exports: $Exports<'sentry-cli-binary'>;
}
declare module 'sentry-cli-binary/index.js' {
  declare module.exports: $Exports<'sentry-cli-binary'>;
}
