// flow-typed signature: 7d56b4410f0f22ad18bccd0b17a3b39d
// flow-typed version: <<STUB>>/standard-react_v^4.0.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'standard-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'standard-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'standard-react/bin/cmd' {
  declare module.exports: any;
}

declare module 'standard-react/options' {
  declare module.exports: any;
}

declare module 'standard-react/test/api' {
  declare module.exports: any;
}

declare module 'standard-react/test/cmd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'standard-react/bin/cmd.js' {
  declare module.exports: $Exports<'standard-react/bin/cmd'>;
}
declare module 'standard-react/index' {
  declare module.exports: $Exports<'standard-react'>;
}
declare module 'standard-react/index.js' {
  declare module.exports: $Exports<'standard-react'>;
}
declare module 'standard-react/options.js' {
  declare module.exports: $Exports<'standard-react/options'>;
}
declare module 'standard-react/test/api.js' {
  declare module.exports: $Exports<'standard-react/test/api'>;
}
declare module 'standard-react/test/cmd.js' {
  declare module.exports: $Exports<'standard-react/test/cmd'>;
}
