// flow-typed signature: 96ac27a33cb8f4aceef790552c3eb83a
// flow-typed version: <<STUB>>/susy_v^2.2.12/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'susy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'susy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'susy/eyeglass-exports' {
  declare module.exports: any;
}

// Filename aliases
declare module 'susy/eyeglass-exports.js' {
  declare module.exports: $Exports<'susy/eyeglass-exports'>;
}
