// flow-typed signature: 0e22a3ed4505686cc42651cdefa61990
// flow-typed version: <<STUB>>/timezones.json_v^1.1.0/flow_v0.59.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'timezones.json'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'timezones.json' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'timezones.json/index' {
  declare module.exports: $Exports<'timezones.json'>;
}
declare module 'timezones.json/index.js' {
  declare module.exports: $Exports<'timezones.json'>;
}
