// flow-typed signature: 43242023b62148869349247475d54a41
// flow-typed version: <<STUB>>/unexpected_v^10.36.0/flow_v0.56.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unexpected'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unexpected' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unexpected/build/lib/addAdditionalPromiseMethods' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/assertions' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/AssertionString' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/createStandardErrorMessage' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/createWrappedExpectProto' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/defaultDepth' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/index' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/isPendingPromise' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/makeDiffResultBackwardsCompatible' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/makePromise' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/notifyPendingPromise' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/oathbreaker' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/specialCharRegExp' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/styles' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/throwIfNonUnexpectedError' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/types' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/Unexpected' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/UnexpectedError' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/useFullStackTrace' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/utils' {
  declare module.exports: any;
}

declare module 'unexpected/build/lib/workQueue' {
  declare module.exports: any;
}

declare module 'unexpected/lib/addAdditionalPromiseMethods' {
  declare module.exports: any;
}

declare module 'unexpected/lib/assertions' {
  declare module.exports: any;
}

declare module 'unexpected/lib/AssertionString' {
  declare module.exports: any;
}

declare module 'unexpected/lib/createStandardErrorMessage' {
  declare module.exports: any;
}

declare module 'unexpected/lib/createWrappedExpectProto' {
  declare module.exports: any;
}

declare module 'unexpected/lib/defaultDepth' {
  declare module.exports: any;
}

declare module 'unexpected/lib/index' {
  declare module.exports: any;
}

declare module 'unexpected/lib/isPendingPromise' {
  declare module.exports: any;
}

declare module 'unexpected/lib/makeDiffResultBackwardsCompatible' {
  declare module.exports: any;
}

declare module 'unexpected/lib/makePromise' {
  declare module.exports: any;
}

declare module 'unexpected/lib/notifyPendingPromise' {
  declare module.exports: any;
}

declare module 'unexpected/lib/oathbreaker' {
  declare module.exports: any;
}

declare module 'unexpected/lib/specialCharRegExp' {
  declare module.exports: any;
}

declare module 'unexpected/lib/styles' {
  declare module.exports: any;
}

declare module 'unexpected/lib/throwIfNonUnexpectedError' {
  declare module.exports: any;
}

declare module 'unexpected/lib/types' {
  declare module.exports: any;
}

declare module 'unexpected/lib/Unexpected' {
  declare module.exports: any;
}

declare module 'unexpected/lib/UnexpectedError' {
  declare module.exports: any;
}

declare module 'unexpected/lib/useFullStackTrace' {
  declare module.exports: any;
}

declare module 'unexpected/lib/utils' {
  declare module.exports: any;
}

declare module 'unexpected/lib/workQueue' {
  declare module.exports: any;
}

declare module 'unexpected/unexpected' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unexpected/build/lib/addAdditionalPromiseMethods.js' {
  declare module.exports: $Exports<'unexpected/build/lib/addAdditionalPromiseMethods'>;
}
declare module 'unexpected/build/lib/assertions.js' {
  declare module.exports: $Exports<'unexpected/build/lib/assertions'>;
}
declare module 'unexpected/build/lib/AssertionString.js' {
  declare module.exports: $Exports<'unexpected/build/lib/AssertionString'>;
}
declare module 'unexpected/build/lib/createStandardErrorMessage.js' {
  declare module.exports: $Exports<'unexpected/build/lib/createStandardErrorMessage'>;
}
declare module 'unexpected/build/lib/createWrappedExpectProto.js' {
  declare module.exports: $Exports<'unexpected/build/lib/createWrappedExpectProto'>;
}
declare module 'unexpected/build/lib/defaultDepth.js' {
  declare module.exports: $Exports<'unexpected/build/lib/defaultDepth'>;
}
declare module 'unexpected/build/lib/index.js' {
  declare module.exports: $Exports<'unexpected/build/lib/index'>;
}
declare module 'unexpected/build/lib/isPendingPromise.js' {
  declare module.exports: $Exports<'unexpected/build/lib/isPendingPromise'>;
}
declare module 'unexpected/build/lib/makeDiffResultBackwardsCompatible.js' {
  declare module.exports: $Exports<'unexpected/build/lib/makeDiffResultBackwardsCompatible'>;
}
declare module 'unexpected/build/lib/makePromise.js' {
  declare module.exports: $Exports<'unexpected/build/lib/makePromise'>;
}
declare module 'unexpected/build/lib/notifyPendingPromise.js' {
  declare module.exports: $Exports<'unexpected/build/lib/notifyPendingPromise'>;
}
declare module 'unexpected/build/lib/oathbreaker.js' {
  declare module.exports: $Exports<'unexpected/build/lib/oathbreaker'>;
}
declare module 'unexpected/build/lib/specialCharRegExp.js' {
  declare module.exports: $Exports<'unexpected/build/lib/specialCharRegExp'>;
}
declare module 'unexpected/build/lib/styles.js' {
  declare module.exports: $Exports<'unexpected/build/lib/styles'>;
}
declare module 'unexpected/build/lib/throwIfNonUnexpectedError.js' {
  declare module.exports: $Exports<'unexpected/build/lib/throwIfNonUnexpectedError'>;
}
declare module 'unexpected/build/lib/types.js' {
  declare module.exports: $Exports<'unexpected/build/lib/types'>;
}
declare module 'unexpected/build/lib/Unexpected.js' {
  declare module.exports: $Exports<'unexpected/build/lib/Unexpected'>;
}
declare module 'unexpected/build/lib/UnexpectedError.js' {
  declare module.exports: $Exports<'unexpected/build/lib/UnexpectedError'>;
}
declare module 'unexpected/build/lib/useFullStackTrace.js' {
  declare module.exports: $Exports<'unexpected/build/lib/useFullStackTrace'>;
}
declare module 'unexpected/build/lib/utils.js' {
  declare module.exports: $Exports<'unexpected/build/lib/utils'>;
}
declare module 'unexpected/build/lib/workQueue.js' {
  declare module.exports: $Exports<'unexpected/build/lib/workQueue'>;
}
declare module 'unexpected/lib/addAdditionalPromiseMethods.js' {
  declare module.exports: $Exports<'unexpected/lib/addAdditionalPromiseMethods'>;
}
declare module 'unexpected/lib/assertions.js' {
  declare module.exports: $Exports<'unexpected/lib/assertions'>;
}
declare module 'unexpected/lib/AssertionString.js' {
  declare module.exports: $Exports<'unexpected/lib/AssertionString'>;
}
declare module 'unexpected/lib/createStandardErrorMessage.js' {
  declare module.exports: $Exports<'unexpected/lib/createStandardErrorMessage'>;
}
declare module 'unexpected/lib/createWrappedExpectProto.js' {
  declare module.exports: $Exports<'unexpected/lib/createWrappedExpectProto'>;
}
declare module 'unexpected/lib/defaultDepth.js' {
  declare module.exports: $Exports<'unexpected/lib/defaultDepth'>;
}
declare module 'unexpected/lib/index.js' {
  declare module.exports: $Exports<'unexpected/lib/index'>;
}
declare module 'unexpected/lib/isPendingPromise.js' {
  declare module.exports: $Exports<'unexpected/lib/isPendingPromise'>;
}
declare module 'unexpected/lib/makeDiffResultBackwardsCompatible.js' {
  declare module.exports: $Exports<'unexpected/lib/makeDiffResultBackwardsCompatible'>;
}
declare module 'unexpected/lib/makePromise.js' {
  declare module.exports: $Exports<'unexpected/lib/makePromise'>;
}
declare module 'unexpected/lib/notifyPendingPromise.js' {
  declare module.exports: $Exports<'unexpected/lib/notifyPendingPromise'>;
}
declare module 'unexpected/lib/oathbreaker.js' {
  declare module.exports: $Exports<'unexpected/lib/oathbreaker'>;
}
declare module 'unexpected/lib/specialCharRegExp.js' {
  declare module.exports: $Exports<'unexpected/lib/specialCharRegExp'>;
}
declare module 'unexpected/lib/styles.js' {
  declare module.exports: $Exports<'unexpected/lib/styles'>;
}
declare module 'unexpected/lib/throwIfNonUnexpectedError.js' {
  declare module.exports: $Exports<'unexpected/lib/throwIfNonUnexpectedError'>;
}
declare module 'unexpected/lib/types.js' {
  declare module.exports: $Exports<'unexpected/lib/types'>;
}
declare module 'unexpected/lib/Unexpected.js' {
  declare module.exports: $Exports<'unexpected/lib/Unexpected'>;
}
declare module 'unexpected/lib/UnexpectedError.js' {
  declare module.exports: $Exports<'unexpected/lib/UnexpectedError'>;
}
declare module 'unexpected/lib/useFullStackTrace.js' {
  declare module.exports: $Exports<'unexpected/lib/useFullStackTrace'>;
}
declare module 'unexpected/lib/utils.js' {
  declare module.exports: $Exports<'unexpected/lib/utils'>;
}
declare module 'unexpected/lib/workQueue.js' {
  declare module.exports: $Exports<'unexpected/lib/workQueue'>;
}
declare module 'unexpected/unexpected.js' {
  declare module.exports: $Exports<'unexpected/unexpected'>;
}
