// @flow

import type {AppAction as _AppAction} from './action-next'

export type MaterialGroup = {
  id: string, // Generated by the frontend
  name: string,
  materials: Array<{
    id: string, // Generated by the frontend
    name: string,
    description: string,
    properties: {
      dishwasherSafe: boolean,
      flexibility: number,
      foodSafe: boolean,
      freedomOfDesign: number,
      interlockingAndEnclosedParts: boolean,
      levelOfDetail: number,
      materialSpec: string,
      postProcessing: number,
      printingMethod: string,
      recyclable: boolean,
      waterproof: boolean
    },
    finishGroups: Array<{
      id: string, // Generated by the frontend
      name: string,
      materialName: string,
      summary: string,
      featuredImage: string,
      materialConfigs: Array<{
        id: string,
        name: string,
        color: string,
        colorCode: string,
        colorImage: string
      }>
    }>
  }>
}

export type UploadingModel = {
  fileId: string,
  fileName: string,
  fileSize: number,
  progress: number
}

export type BackendModel = {
  modelId: string,
  fileName: string,
  fileUnit: 'mm' | 'cm' | 'in',
  area: ?number,
  volume: ?number,
  dimensions: {
    x: ?number,
    y: ?number,
    z: ?number
  },
  thumbnailUrl: string
}

export type Model = BackendModel & {
  quantity: number,
  fileSize: number
}

export type Location = {
  city: string,
  zipCode: string,
  stateCode: string,
  countryCode: string
}

export type Address = Location & {
  firstName: string,
  lastName: string,
  street: string,
  houseNumber: string,
  addressLine2: string
}

export type GoogleMapsPlace = {
  address_components: ?Array<{
    types: Array<string>,
    short_name: string
  }>
}

export type ModalContent = 'PICK_LOCATION' | 'FATAL_ERROR'

type _ModalConfig<C> = {
  isCloseable: boolean,
  content: C,
  contentArgs: any
}

export type ModalConfig = _ModalConfig<null | ModalContent>

export type OpenModalConfig = _ModalConfig<ModalContent>

export type UserState = {
  userId: string | null,
  location: Location | null,
  currency: string
}

export type CoreState = {
  models: Array<Model>,
  uploadingModels: Array<UploadingModel>,
  materialGroups: Array<MaterialGroup>
}

export type ModalState = ModalConfig & {
  isOpen: boolean
}

export type State = {
  core: CoreState,
  modal: ModalState,
  user: UserState,
  routing: any, // Managed by react-router-redux
  form: any // Managed by redux-form
}

export type Action<Type, Payload> = {
  type: Type,
  payload: Payload
}

export type AppAction = _AppAction
